### ISSUE TITLE
Koa version not working

### ISSUE THREAD

**Issue by Vavassor** [wryk/tusky-api#1]
The package asks for `"koa": "^2.2.0"` but running the 2.2.0 version gave me this error:
```May 25 22:13:02 mqtt-test npm[9339]: > tusky-api@0.0.0 server /home/tusky/tusky-api
May 25 22:13:02 mqtt-test npm[9339]: > babel-node ./lib/server.js
May 25 22:13:06 mqtt-test npm[9339]: /home/tusky/tusky-api/node_modules/koa/lib/response.js:47
May 25 22:13:06 mqtt-test npm[9339]:     const { res } = this;
May 25 22:13:06 mqtt-test npm[9339]:           ^
May 25 22:13:06 mqtt-test npm[9339]: SyntaxError: Unexpected token {
May 25 22:13:06 mqtt-test npm[9339]:     at exports.runInThisContext (vm.js:53:16)
May 25 22:13:06 mqtt-test npm[9339]:     at Module._compile (module.js:374:25)
May 25 22:13:06 mqtt-test npm[9339]:     at Module._extensions..js (module.js:417:10)
May 25 22:13:06 mqtt-test npm[9339]:     at Object.require.extensions.(anonymous function) [as .js] (/home/tusky/tusky-api/node_modules/babel-register/lib/node.js:152:7)
May 25 22:13:06 mqtt-test npm[9339]:     at Module.load (module.js:344:32)
May 25 22:13:06 mqtt-test npm[9339]:     at Function.Module._load (module.js:301:12)
May 25 22:13:06 mqtt-test npm[9339]:     at Module.require (module.js:354:17)
May 25 22:13:06 mqtt-test npm[9339]:     at require (internal/module.js:12:17)
May 25 22:13:06 mqtt-test npm[9339]:     at Object.<anonymous> (/home/tusky/tusky-api/node_modules/koa/lib/application.js:11:18)
May 25 22:13:06 mqtt-test npm[9339]:     at Module._compile (module.js:410:26)
May 25 22:13:06 mqtt-test npm[9339]:     at Module._extensions..js (module.js:417:10)
May 25 22:13:06 mqtt-test npm[9339]:     at Object.require.extensions.(anonymous function) [as .js] (/home/tusky/tusky-api/node_modules/babel-register/lib/node.js:152:7)
May 25 22:13:06 mqtt-test npm[9339]:     at Module.load (module.js:344:32)
May 25 22:13:06 mqtt-test npm[9339]:     at Function.Module._load (module.js:301:12)
May 25 22:13:06 mqtt-test npm[9339]:     at Module.require (module.js:354:17)
May 25 22:13:06 mqtt-test npm[9339]:     at require (internal/module.js:12:17)
```
I was able to replace the package with version `koa@2.0.0-alpha.7` which didn't cause this error. I think it's connected to this upstream issue but I'm not sure the specifics koajs/koa#938.

**Comment by wryk** [comment]
koa require recent nodejs version, updating to v7.6.0 or higher will fix this error

Or I can replace koa by a more friendly lib with old nodejs versions

**Comment by Vavassor** [comment]
Ah, apparently the "nodejs" package in one of ubuntu's repositories was carrying an old version (4.2.6) of node.js and that's how I installed it. So, my mistake. I was able to upgrade it so koa 2.2.0 works fine now.
